import Head from 'next/head'
import Main from '@/components/Main'
import About from '@/components/About'
import Skills from '@/components/Skills'
import Resume from '@/components/Resume'
import Projects from '@/components/Projects'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Contact from '@/components/Contact'

// import { Inter } from '@next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Emily Ryan | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin></link>
        {/* <link href="https://fonts.googleapis.com/css2?family=Cabin&family=Josefin+Slab&family=Unbounded&display=swap" rel="stylesheet"></link> */}

      </Head>
      <Navbar/>
      <Main/>
      <About/>
      <Skills/>
      <Resume/>
      <Projects/>
      <Contact/>
    </>
  )
}
